# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of file')),
                ('path', models.CharField(max_length=100, verbose_name='Path of file')),
            ],
        ),
    ]
